/// Multi-language Localized Strings for Devavani
/// Primary language: Hindi (hi)
/// Supported languages: Nepali (ne), English (en)
class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _localizedValues = {
    'hi': {
      'appName': 'देववाणी',
      'morningGreeting': 'प्रातः वंदना • शुभ प्रभात',
      'namaste': 'नमस्ते',
      'auspiciousDay': 'आज का दिन मंगलमय हो',
      'mainPrayerBadge': 'मुख्य प्रार्थना',
      'aartiCardTitle': 'आज की आरती / चालीसा',
      'aartiCardSub': 'श्री हनुमान चालीसा',
      'jaapCardTitle': 'जाप शुरू करें',
      'jaapCardSub': 'माला का ध्यान और स्मरण',
      'panchangCardTitle': 'आज का पंचांग',
      'panchangCardSub': 'शुभ मुहूर्त व आज की तिथि',
      
      'navHome': 'होम',
      'navAarti': 'आरती',
      'navJaap': 'जाप',
      'navMore': 'अन्य',

      'jaapTitle': 'जाप',
      'changeMantra': 'मंत्र बदलें',
      'tapAnywherePrompt': 'स्क्रीन पर कहीं भी स्पर्श करें',
      'target108': 'लक्ष्य: १०८',
      'jaapCompleted': 'जाप पूर्ण',
      'todayTotal': 'आज का कुल',
      'malasCompleted': 'माला पूर्ण',
      'malasSuffix': 'माला (१०८)',
      'jaapUnit': 'जाप',
      'inspirationTitle': 'सद्प्रेरणा',
      'inspirationQuote': 'शांत भाव से एक-एक नाम का उच्चारण करें। मन को श्वास के साथ जोड़ें।',
      'vibrationOn': 'कंपन: चालू',
      'vibrationOff': 'कंपन: बंद',
      'soundBell': 'ध्वनि: घंटी',
      'soundOff': 'ध्वनि: बंद',
      'resetCounter': 'पुनः सेट करें (नया जाप)',
      'resetConfirmTitle': 'जाप पुनः सेट करें?',
      'resetConfirmMsg': 'क्या आप जाप संख्या शून्य (०) करना चाहते हैं?',
      'resetConfirmYes': 'हाँ, नया जाप शुरू करें',
      'cancel': 'रद्द करें',
      'selectMantraTitle': 'पवित्र मंत्र चुनें',

      'aartiPlayerTitle': 'आरती',
      'morningAartiBadge': 'प्रातः आरती',
      'bhaktiRasBadge': 'भक्ति रस',
      'hanumanChalisaTitle': 'श्री हनुमान चालीसा',
      'sankatMochanSubtitle': 'संकट मोचन कृपा',
      'holyVersesHeader': 'पवित्र दोहा एवं चौपाई',
      'elapsedTime': 'बीता समय',
      'totalTime': 'कुल समय',
      'rewind10': '१० से.',
      'forward10': '१० से.',
      'loopAarti': 'आरती दोहराएं (Loop)',
      'peaceFooter': 'ॐ शांति • श्रद्धा और भक्ति भाव से प्रभु का ध्यान करें',
      'fontSizeInc': 'अ A+',
      'fontSizeDec': 'अ A-',

      'panchangTitle': 'आज का पंचांग',
      'mainTithi': 'आज की मुख्य तिथि',
      'tithiDetail': 'शुक्ल पक्ष एकादशी',
      'specialDayBadge': 'अमलकी एकादशी (अति शुभ दिन)',
      'sunrise': 'सूर्योदय',
      'sunset': 'सूर्यास्त',
      'whatToDo': 'आज क्या करें',
      'whatToAvoid': 'आज क्या न करें',

      'godOfTheDayTitle': 'आज के देवता: श्री गणेश जी',
      'godDayBadge': 'बुधवार विशेष • विघ्नहर्ता',
      'godStory': 'भगवान श्री गणेश विघ्नहर्ता और प्रथम पूज्य देव हैं। आज के दिन गणेश जी का स्मरण करने से बुद्धि, सुख और शांति प्राप्त होती है।',
      'ganeshaMantraTitle': 'सिद्ध गणेश महामंत्र',
      'ganeshaMantraText': 'ॐ गं गणपतये नमः',
      'ganeshaMantraMeaning': 'भावार्थ: हे विघ्नहर्ता, हमारे सभी कष्ट दूर करें।',
      'listenMantraChant': 'मंत्र जप सुनें (11 बार)',
      'listeningMantra': 'मंत्र जप चल रहा है...',
      'digitalFlowerTitle': 'डिजिटल पुष्प अर्पण',
      'digitalFlowerSub': 'गणपति बप्पा के चरणों में फूल चढ़ाएं',
      'offerFlowerBtn': 'पुष्प अर्पित करें',
      'flowerOfferedToast': 'पुष्प समर्पित हुआ! गणपति बाप्पा मोरिया!',
      'settingsHeader': 'सुविधा व भाषा सेटिंग्स',
      'languageSetting': 'भाषा (Language)',
      'brahmaMuhurtaReminder': 'ब्रह्म मुहूर्त प्रार्थना सूचना (प्रातः 05:00)',
      'fontSizeSetting': 'अक्षर आकार (Text Size)',
      'offlineReady': 'सभी मुख्य प्रार्थनाएं ऑफ़लाइन उपलब्ध हैं',
      'back': 'पीछे जाएं',
      'profile': 'प्रोफाइल',
      'settingsScreenTitle': 'सेटिंग्स / मेरी प्राथमिकताएँ',
      'chooseLanguage': 'भाषा चुनें (Language)',
      'dailyRemindersTitle': 'दैनिक स्मरण (Daily Reminders)',
      'morningReminder': 'सुबह का स्मरण',
      'morningReminderSub': 'प्रातः आरती व मंगलमय शुरुआत के लिए स्मरण',
      'eveningReminder': 'शाम का स्मरण',
      'eveningReminderSub': 'संध्या आरती व दीप प्रज्वलन के लिए स्मरण',
      'customTime': 'अन्य समय...',
      'notificationPreviewTitle': 'आज का पावन संदेश (पूर्वावलोकन)',
      'testNotificationBtn': 'सूचना परीक्षण करें (Test)',
      'reminderActiveAt': 'स्मरण समय',
    },
    'ne': {
      'appName': 'देववाणी',
      'morningGreeting': 'प्रातः वन्दना • शुभ प्रभात',
      'namaste': 'नमस्ते',
      'auspiciousDay': 'आजको दिन मङ्गलमय रहोस्',
      'mainPrayerBadge': 'मुख्य प्रार्थना',
      'aartiCardTitle': 'आजको आरती / चालीसा',
      'aartiCardSub': 'श्री हनुमान चालीसा',
      'jaapCardTitle': 'जाप सुरु गर्नुहोस्',
      'jaapCardSub': 'मालाको ध्यान र स्मरण',
      'panchangCardTitle': 'आजको पञ्चाङ्ग',
      'panchangCardSub': 'शुभ मुहूर्त र आजको तिथि',

      'navHome': 'गृह',
      'navAarti': 'आरती',
      'navJaap': 'जाप',
      'navMore': 'अन्य',

      'jaapTitle': 'जाप',
      'changeMantra': 'मन्त्र बदल्नुहोस्',
      'tapAnywherePrompt': 'स्क्रिनमा जहाँ पनि छुनुहोस्',
      'target108': 'लक्ष्य: १०८',
      'jaapCompleted': 'जाप पूर्ण',
      'todayTotal': 'आजको कुल',
      'malasCompleted': 'माला पूर्ण',
      'malasSuffix': 'माला (१०८)',
      'jaapUnit': 'जाप',
      'inspirationTitle': 'सद्प्रेरणा',
      'inspirationQuote': 'शान्त भावले एक-एक नामको उच्चारण गर्नुहोस्। मनलाई श्वाससँग जोड्नुहोस्।',
      'vibrationOn': 'कम्पन: चालु',
      'vibrationOff': 'कम्पन: बन्द',
      'soundBell': 'ध्वनि: घण्टी',
      'soundOff': 'ध्वनि: बन्द',
      'resetCounter': 'पुनः सेट गर्नुहोस् (नयाँ जाप)',
      'resetConfirmTitle': 'जाप पुनः सेट गर्नुहुन्छ?',
      'resetConfirmMsg': 'के तपाईं जाप संख्या शून्य (०) गर्न चाहनुहुन्छ?',
      'resetConfirmYes': 'हो, नयाँ जाप सुरु गर्नुहोस्',
      'cancel': 'रद्द गर्नुहोस्',
      'selectMantraTitle': 'पवित्र मन्त्र रोज्नुहोस्',

      'aartiPlayerTitle': 'आरती',
      'morningAartiBadge': 'प्रातः आरती',
      'bhaktiRasBadge': 'भक्ति रस',
      'hanumanChalisaTitle': 'श्री हनुमान चालीसा',
      'sankatMochanSubtitle': 'सङ्कट मोचन कृपा',
      'holyVersesHeader': 'पवित्र दोहा एवं चौपाई',
      'elapsedTime': 'बितेको समय',
      'totalTime': 'कुल समय',
      'rewind10': '१० से.',
      'forward10': '१० से.',
      'loopAarti': 'आरती दोहोर्याउनुहोस् (Loop)',
      'peaceFooter': 'ॐ शान्ति • श्रद्धा र भक्ति भावले प्रभुको ध्यान गर्नुहोस्',
      'fontSizeInc': 'अ A+',
      'fontSizeDec': 'अ A-',

      'panchangTitle': 'आजको पञ्चाङ्ग',
      'mainTithi': 'आजको मुख्य तिथि',
      'tithiDetail': 'शुक्ल पक्ष एकादशी',
      'specialDayBadge': 'अमलकी एकादशी (अति शुभ दिन)',
      'sunrise': 'सूर्योदय',
      'sunset': 'सूर्यास्त',
      'whatToDo': 'आज के गर्ने',
      'whatToAvoid': 'आज के नगर्ने',

      'godOfTheDayTitle': 'आजका देवता: श्री गणेश जी',
      'godDayBadge': 'बुधवार विशेष • विघ्नहर्ता',
      'godStory': 'भगवान श्री गणेश विघ्नहर्ता र प्रथम पूज्य देव हुनुहुन्छ। आजको दिन गणेश जीको स्मरण गर्दा बुद्धि, सुख र शान्ति मिल्छ।',
      'ganeshaMantraTitle': 'सिद्ध गणेश महामन्त्र',
      'ganeshaMantraText': 'ॐ गं गणपतये नमः',
      'ganeshaMantraMeaning': 'भावार्थ: हे विघ्नहर्ता, हाम्रा सम्पूर्ण कष्टहरू निवारण गर्नुहोस्।',
      'listenMantraChant': 'मन्त्र जप सुन्नुहोस् (११ पटक)',
      'listeningMantra': 'मन्त्र जप चल्दैछ...',
      'digitalFlowerTitle': 'डिजिटल पुष्प अर्पण',
      'digitalFlowerSub': 'गणपति बाप्पाको चरणमा फूल चढाउनुहोस्',
      'offerFlowerBtn': 'पुष्प अर्पित गर्नुहोस्',
      'flowerOfferedToast': 'पुष्प समर्पित भयो! गणपति बाप्पा मोरिया!',
      'settingsHeader': 'सुविधा र भाषा सेटिङ',
      'languageSetting': 'भाषा (Language)',
      'brahmaMuhurtaReminder': 'ब्रह्म मुहूर्त प्रार्थना सूचना (प्रातः ०५:००)',
      'fontSizeSetting': 'अक्षरको आकार (Text Size)',
      'offlineReady': 'सबै मुख्य प्रार्थनाहरू अफलाइन उपलब्ध छन्',
      'back': 'पछाडि जानुहोस्',
      'profile': 'प्रोफाइल',
      'settingsScreenTitle': 'सेटिङहरू / मेरा प्राथमिकताहरू',
      'chooseLanguage': 'भाषा रोज्नुहोस् (Language)',
      'dailyRemindersTitle': 'दैनिक स्मरण (Daily Reminders)',
      'morningReminder': 'बिहानको स्मरण',
      'morningReminderSub': 'बिहानको आरती र मङ्गलमय सुरुवातको लागि स्मरण',
      'eveningReminder': 'बेलुकीको स्मरण',
      'eveningReminderSub': 'सन्ध्या आरती र दीप प्रज्वलनको लागि स्मरण',
      'customTime': 'अन्य समय...',
      'notificationPreviewTitle': 'आजको पावन सन्देश (पूर्वावलोकन)',
      'testNotificationBtn': 'सूचना परीक्षण गर्नुहोस्',
      'reminderActiveAt': 'स्मरण समय',
    },
    'en': {
      'appName': 'Devavani',
      'morningGreeting': 'Morning Prayers • Auspicious Dawn',
      'namaste': 'Namaste',
      'auspiciousDay': 'May your day be blessed and peaceful',
      'mainPrayerBadge': 'Main Prayer',
      'aartiCardTitle': "Today's Aarti / Chalisa",
      'aartiCardSub': 'Shri Hanuman Chalisa',
      'jaapCardTitle': 'Start Jaap (Chanting)',
      'jaapCardSub': 'Mala contemplation & meditation',
      'panchangCardTitle': "Today's Panchang",
      'panchangCardSub': 'Auspicious timings & today tithi',

      'navHome': 'Home',
      'navAarti': 'Aarti',
      'navJaap': 'Jaap',
      'navMore': 'More',

      'jaapTitle': 'Jaap Counter',
      'changeMantra': 'Change Mantra',
      'tapAnywherePrompt': 'Tap anywhere on screen',
      'target108': 'Target: 108',
      'jaapCompleted': 'Jaap Complete',
      'todayTotal': "Today's Total",
      'malasCompleted': 'Malas Done',
      'malasSuffix': 'Malas (108)',
      'jaapUnit': 'Chants',
      'inspirationTitle': 'Daily Inspiration',
      'inspirationQuote': 'Chant with peaceful devotion. Connect your mind with gentle breathing.',
      'vibrationOn': 'Haptic: On',
      'vibrationOff': 'Haptic: Off',
      'soundBell': 'Sound: Bell',
      'soundOff': 'Sound: Off',
      'resetCounter': 'Reset Counter (New Mala)',
      'resetConfirmTitle': 'Reset Jaap Counter?',
      'resetConfirmMsg': 'Do you want to reset the count to zero (0)?',
      'resetConfirmYes': 'Yes, Start New Jaap',
      'cancel': 'Cancel',
      'selectMantraTitle': 'Select Sacred Mantra',

      'aartiPlayerTitle': 'Aarti Player',
      'morningAartiBadge': 'Morning Aarti',
      'bhaktiRasBadge': 'Devotion',
      'hanumanChalisaTitle': 'Shri Hanuman Chalisa',
      'sankatMochanSubtitle': 'Dispeller of all Sorrows',
      'holyVersesHeader': 'Sacred Doha & Chaupai Verses',
      'elapsedTime': 'Elapsed',
      'totalTime': 'Total',
      'rewind10': '10s',
      'forward10': '10s',
      'loopAarti': 'Loop Aarti Continuously',
      'peaceFooter': 'Om Shanti • Meditate upon the Lord with deep love and devotion',
      'fontSizeInc': 'A+',
      'fontSizeDec': 'A-',

      'panchangTitle': "Today's Panchang",
      'mainTithi': "Today's Main Tithi",
      'tithiDetail': 'Shukla Paksha Ekadashi',
      'specialDayBadge': 'Amalaki Ekadashi (Highly Auspicious)',
      'sunrise': 'Sunrise',
      'sunset': 'Sunset',
      'whatToDo': 'What To Do',
      'whatToAvoid': 'What To Avoid',

      'godOfTheDayTitle': 'Deity of the Day: Shri Ganesha',
      'godDayBadge': 'Wednesday Special • Vighnaharta',
      'godStory': 'Lord Ganesha is the remover of all obstacles and the first worshipped deity. Remembering Ganesha brings wisdom, peace, and auspiciousness.',
      'ganeshaMantraTitle': 'Siddha Ganesha Mahamantra',
      'ganeshaMantraText': 'Om Gam Ganapataye Namah',
      'ganeshaMantraMeaning': 'Meaning: O Remover of Obstacles, bless our life with peace and grace.',
      'listenMantraChant': 'Listen to Chant (11x)',
      'listeningMantra': 'Playing sacred chant...',
      'digitalFlowerTitle': 'Digital Flower Offering',
      'digitalFlowerSub': 'Offer sacred flowers at Lord Ganesha’s feet',
      'offerFlowerBtn': 'Offer Flowers',
      'flowerOfferedToast': 'Flowers offered with love! Ganapati Bappa Morya!',
      'settingsHeader': 'Preferences & Settings',
      'languageSetting': 'App Language',
      'brahmaMuhurtaReminder': 'Brahma Muhurta Prayer Alarm (05:00 AM)',
      'fontSizeSetting': 'Reading Text Size',
      'offlineReady': 'All primary prayers are available offline',
      'back': 'Go Back',
      'profile': 'Profile',
      'settingsScreenTitle': 'Settings / My Preferences',
      'chooseLanguage': 'Choose Language',
      'dailyRemindersTitle': 'Daily Reminders',
      'morningReminder': 'Morning Reminder',
      'morningReminderSub': 'Reminder for morning Aarti & auspicious start',
      'eveningReminder': 'Evening Reminder',
      'eveningReminderSub': 'Reminder for evening Aarti & twilight prayer',
      'customTime': 'Custom Time...',
      'notificationPreviewTitle': "Today's Sacred Message (Preview)",
      'testNotificationBtn': 'Test Reminder Now',
      'reminderActiveAt': 'Scheduled Time',
    },
  };

  static String get(String key, {String lang = 'hi'}) {
    return _localizedValues[lang]?[key] ?? _localizedValues['hi']?[key] ?? key;
  }
}
